# Generated by Django 4.1.7 on 2023-05-05 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0008_cart_cartitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
